//-----------------------------------------------------------------
// Windows Material Importer Class
// 
// Derived class for importing material descripton from JSON and make them manager ready
//-----------------------------------------------------------------

//-----------------------------------------------------------------
// Include Files
//-----------------------------------------------------------------
#include "rapidjson/document.h"
#include "WinFileRawDataReader.h"
#include "WinMaterialImporter.h"
#include "RenderingPass.h"

using namespace Emerald;

WinMaterialImporter::WinMaterialImporter()
{

}

WinMaterialImporter::~WinMaterialImporter()
{

}

Material* WinMaterialImporter::LoadMaterial(const std::wstring& matName, Resource::ResourceID matID, Error& err) const
{
    Material* pMaterial = new Material(matID, matName);
    WinFileRawDataReader fileReader;
    Error localError;

    localError = fileReader.LoadRawData(L"assets\\materials\\" + matName + L".material");
    if (localError)
    {
        err += localError;
        return nullptr;
    }
    std::wstring sourceText = StringUtilities::DecodeStringBytes(65001, fileReader.GetBuffer(), fileReader.GetBufferSize(), 0, localError);
    if (localError)
    {
        err += localError;
        return nullptr;
    }

    //extract passes
    using namespace rapidjson;
    GenericDocument<UTF16LE<>> jsonDoc;
    if (jsonDoc.Parse(sourceText.c_str()).HasParseError())
    {
        err += L"Material " + matName + L" json parse failed.";
        return nullptr;
    }

    //no content validation here because the json will be generated by engine automatically in production
    for (auto& p : jsonDoc[L"passes"].GetArray())
    {
        RenderingPass newPass;
        auto passObject = p.GetObj();
        newPass.SetName(passObject[L"name"].GetString());
        newPass.SetShaderProgramName(passObject[L"program"].GetString());
        newPass.SetParent(pMaterial);
        ShaderInputDataDescriptor::DataType dataType = ShaderInputDataDescriptor::DataType::Unknown;
        ShaderType shaderType = ShaderType::Unknown;
        for (auto& param : p[L"parameters"].GetArray())
        {
            if (param[L"shaderType"].GetString() == L"Vertex")
            {
                shaderType = ShaderType::Vertex;
            }
            else if (param[L"shaderType"].GetString() == L"Fragment")
            {
                shaderType = ShaderType::Fragment;
            }

            std::wstring paramType = param[L"type"].GetString();
            float* pValues = nullptr;
            if (paramType == L"Scalar")
            {
                dataType = ShaderInputDataDescriptor::DataType::Scalar;
                pValues = new float[2];//make it an array so we can use delete [] as well later
                *pValues = param[L"value"].GetFloat();
                *(pValues + 1) = 0;//dummy
            }
            else if (paramType == L"Vector2")
            {
                dataType = ShaderInputDataDescriptor::DataType::Vector2;
                pValues = new float[2];
                *pValues = (param[L"value"].GetArray())[0].GetFloat();
                *(pValues + 1) = (param[L"value"].GetArray())[1].GetFloat();
            }
            else if (paramType == L"Vector3")
            {
                dataType = ShaderInputDataDescriptor::DataType::Vector3;
                pValues = new float[3];
                *pValues = (param[L"value"].GetArray())[0].GetFloat();
                *(pValues + 1) = (param[L"value"].GetArray())[1].GetFloat();
                *(pValues + 2) = (param[L"value"].GetArray())[2].GetFloat();
            }
            else if (paramType == L"Vector4")
            {
                dataType = ShaderInputDataDescriptor::DataType::Vector4;
                pValues = new float[4];
                *pValues = (param[L"value"].GetArray())[0].GetFloat();
                *(pValues + 1) = (param[L"value"].GetArray())[1].GetFloat();
                *(pValues + 2) = (param[L"value"].GetArray())[2].GetFloat();
                *(pValues + 3) = (param[L"value"].GetArray())[3].GetFloat();
            }
            else if (paramType == L"Matrix3")
            {
                dataType = ShaderInputDataDescriptor::DataType::Matrix3;
                pValues = new float[9];
                for (int i = 0; i < 9; i++)
                {
                    *(pValues + i) = (param[L"value"].GetArray())[i].GetFloat();
                }
            }
            else if (paramType == L"Matrix4")
            {
                dataType = ShaderInputDataDescriptor::DataType::Matrix4;
                pValues = new float[16];
                for (int i = 0; i < 16; i++)
                {
                    *(pValues + i) = (param[L"value"].GetArray())[i].GetFloat();
                }
            }
            newPass.SetInputData(param[L"name"].GetString(), dataType, pValues, shaderType, err);
            SAFE_DELETEARRAY(pValues);
        }

        pMaterial->AddPass(newPass);
    }

    return pMaterial;
}